boot.o: boot.S multiboot.h x86_desc.h types.h
x86_desc.o: x86_desc.S x86_desc.h types.h
exceptions.o: exceptions.c idt.h x86_desc.h types.h lib.h exceptions.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c idt.h x86_desc.h types.h lib.h exceptions.h interrupt_linkage.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h idt.h exceptions.h
lib.o: lib.c lib.h types.h
interrupt_linkage.o interrupt_linkage.S interrupt_linkage.h lib.h interrupts.h
interrupts.o interrupts.c interrupts.h lib.h i8259.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h
