boot.o: boot.S multiboot.h x86_desc.h types.h
interrupt_linkage.o: interrupt_linkage.S interrupt_linkage.h
x86_desc.o: x86_desc.S x86_desc.h types.h
exceptions.o: exceptions.c idt.h x86_desc.h types.h lib.h interrupts.h \
  i8259.h exceptions.h
i8259.o: i8259.c i8259.h types.h lib.h interrupts.h
idt.o: idt.c idt.h x86_desc.h types.h lib.h interrupts.h i8259.h \
  exceptions.h
interrupts.o: interrupts.c interrupts.h lib.h types.h i8259.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h interrupts.h \
  i8259.h debug.h tests.h idt.h exceptions.h rtc.h keyboard.h
keyboard.o: keyboard.c keyboard.h i8259.h types.h
lib.o: lib.c lib.h types.h interrupts.h i8259.h
rtc.o: rtc.c rtc.h types.h lib.h interrupts.h i8259.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h interrupts.h i8259.h \
  idt.h exceptions.h
