boot.o: boot.S multiboot.h x86_desc.h types.h
interrupt_linkage.o: interrupt_linkage.S interrupt_linkage.h interrupts.h \
  lib.h types.h i8259.h rtc_driver.h rtc.h
x86_desc.o: x86_desc.S x86_desc.h types.h
exceptions.o: exceptions.c idt.h interrupt_linkage.h interrupts.h lib.h \
  types.h i8259.h rtc_driver.h rtc.h x86_desc.h exceptions.h
i8259.o: i8259.c i8259.h types.h lib.h interrupts.h rtc_driver.h rtc.h
idt.o: idt.c idt.h interrupt_linkage.h interrupts.h lib.h types.h i8259.h \
  rtc_driver.h rtc.h x86_desc.h exceptions.h
interrupts.o: interrupts.c interrupts.h lib.h types.h i8259.h \
  rtc_driver.h rtc.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h interrupts.h \
  i8259.h rtc_driver.h rtc.h debug.h tests.h idt.h interrupt_linkage.h \
  exceptions.h keyboard.h paging.h
keyboard.o: keyboard.c keyboard.h i8259.h types.h lib.h interrupts.h \
  rtc_driver.h rtc.h
lib.o: lib.c lib.h types.h interrupts.h i8259.h rtc_driver.h rtc.h
paging.o: paging.c paging.h lib.h types.h interrupts.h i8259.h \
  rtc_driver.h rtc.h
rtc.o: rtc.c rtc.h types.h lib.h interrupts.h i8259.h rtc_driver.h
rtc_driver.o: rtc_driver.c rtc_driver.h lib.h types.h interrupts.h \
  i8259.h rtc.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h interrupts.h i8259.h \
  rtc_driver.h rtc.h idt.h interrupt_linkage.h exceptions.h
